# Generated by Django 5.2.5 on 2025-08-30 07:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dataset', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the dataset')),
                ('dataset_type', models.CharField(choices=[('employee', 'Employee Data'), ('budget', 'Budget Data'), ('performance', 'Performance Data'), ('financial', 'Financial Data'), ('custom', 'Custom Dataset')], default='custom', max_length=20)),
                ('csv_file', models.FileField(help_text='Upload CSV file', upload_to='datasets/')),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('row_count', models.IntegerField(blank=True, help_text='Number of rows in the dataset', null=True)),
                ('column_count', models.IntegerField(blank=True, help_text='Number of columns in the dataset', null=True)),
                ('columns_info', models.JSONField(default=dict, help_text='Information about columns (names, types, descriptions)')),
                ('sample_data', models.JSONField(default=list, help_text='Sample rows for preview')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('processing', 'Processing'), ('error', 'Error')], default='processing', max_length=20)),
                ('processing_errors', models.TextField(blank=True, help_text='Any errors during processing')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this dataset is public to all users')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'Viewed'), ('query', 'Queried'), ('download', 'Downloaded'), ('share', 'Shared')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('query_text', models.TextField(blank=True, help_text='The query that was made')),
                ('result_summary', models.TextField(blank=True, help_text='Summary of the query results')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='chat.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
